# Generated by Django 4.1.6 on 2023-02-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogue', '0001_initial'),
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.produit')),
            ],
        ),
        migrations.CreateModel(
            name='EtatCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_totale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addresse_du_livraison', models.TextField(max_length=150)),
                ('mode_de_paiment', models.CharField(max_length=60)),
                ('articles', models.ManyToManyField(to='Commandes.articlecommande')),
                ('etat_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commandes.etatcommande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.utilisateur')),
            ],
        ),
    ]
