# Generated by Django 4.1.6 on 2023-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='stripe_payment_id',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(related_name='produits', to='Commandes.articlecommande'),
        ),
    ]
