# Generated by Django 4.1.6 on 2023-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(upload_to='photos-produits/'),
        ),
    ]
