# Generated by Django 4.1.6 on 2023-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_alter_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(upload_to='photos-produits'),
        ),
    ]
